AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  iam-ssh-agent

  Sample SAM Template for iam-ssh-agent

Parameters:
  AccountIds:
    Type: CommaDelimitedList
    Description: AWS AccountIds whose IAM entities should be allowed to access the API Gateway.
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    Runtime: nodejs12.x
    Environment:
      Variables:
        KEY_PERMISSIONS_TABLE_NAME: !Ref ResourcePermissionTable
  Api:
    Auth:
      DefaultAuthorizer: AWS_IAM
      InvokeRole: NONE
      ResourcePolicy:
        AwsAccountWhitelist: !Ref AccountIds
    EndpointConfiguration: REGIONAL

Resources:
  ListIdentitiesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: ssh-agent-backend/
      Handler: ListIdentities.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ResourcePermissionTable
        - SSMParameterReadPolicy:
            ParameterName: "*/deploy-key.pub"
      Events:
        SSHAgentBackend:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /identities
            Method: get
  ListIdentitiesLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: ListIdentitiesFunction
    Properties:
      RetentionInDays: 1
      LogGroupName:
        !Sub
        - '/aws/lambda/${LambdaName}'
        - LambdaName: !Ref ListIdentitiesFunction
  GetSignatureFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ssh-agent-backend/
      Handler: GetSignature.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ResourcePermissionTable
        - SSMParameterReadPolicy:
            ParameterName: "*/deploy-key*"
        - KMSDecryptPolicy:
            KeyId: aws/ssm
      Events:
        SSHAgentBackend:
          Type: Api
          Properties:
            Path: /signature
            Method: post
  GetSignatureLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: GetSignatureFunction
    Properties:
      RetentionInDays: 1
      LogGroupName:
        !Sub
        - '/aws/lambda/${LambdaName}'
        - LambdaName: !Ref GetSignatureFunction
  ResourcePermissionTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: IamEntityUniqueId
        Type: String

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Api:
    Description: "API Gateway endpoint URL for Prod stage for SSH Agent Backend"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
