#!/bin/bash

set -euxo pipefail

# Build deb
rm -r target/debian/*
docker run --rm --volume $PWD:/workspace --workdir /workspace cargo-deb

# Build and push docker image
docker build --no-cache --tag iam-ssh-agent --squash .
docker tag iam-ssh-agent:latest keithduncan/iam-ssh-agent:latest
docker push keithduncan/iam-ssh-agent:latest
