[package]
name = "agent"
version = "0.1.0"
authors = ["Keith Duncan <keith_duncan@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ssh-agent = "0.2.1"
clap = "2.33.0"
rusoto_core = "0.42.0"